### ISSUE TITLE
Error in the log

### ISSUE THREAD

**Issue by CorruptComputer** [rallion/depressurizer#22]
19:05:17.693869 -  ERR: Error opening Steam config file: System.IO.FileNotFoundException: Could not find file 'c:\program files (x86)\steam\userdata\85729560\760\screenshots.vdf'.
File name: 'c:\program files (x86)\steam\userdata\85729560\760\screenshots.vdf'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at Depressurizer.GameList.LoadShortcutLaunchIds(Int64 SteamId, StringDictionary& shortcutLaunchIds)

It still works fine though.

**Comment by rallion** [comment]
This is fine, unless you have problems with non-steam game handling. It should probably be a "warning" instead of an "error," but I'm not too worried about it to be honest.
