### ISSUE TITLE
Program crashes when anything entered into "Search" field

### ISSUE THREAD

**Issue by lainverse** [rallion/depressurizer#29]
Program version: 0.6.1.0

A fatal error has occurred in Depressurizer. The program will now terminate.

NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.ShouldDisplayGame(GameInfo g)
   at Depressurizer.FormMain.ShouldHideGame(GameInfo g)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Depressurizer.FormMain.UpdateGameList()
   at Depressurizer.FormMain.txtSearch_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
   at System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Just in case here is my prefs and library: https://dl.dropboxusercontent.com/u/11450709/Depressurizer-lib.zip

**Comment by lainverse** [comment]
Seems like I noticed the source of the issue myself.
Somehow "Twin Sector" (27900) end up without a name.
So, if some game name is empty program crashes. I think it still have to be fixed. Program shouldn't crash from something as simple as that.

**Comment by keringar** [comment]
I have fixed the bug by adding a check for null strings in the method FillGameList(), it then replaces any games with a null name with a empty string. It doesn't crash the program but still shows up as an empty title for the user to fix. How do I submit a pull request? (new to github)
