### ISSUE TITLE
Unexpected character '36' found when expecting key

### ISSUE THREAD

**Issue by Hacksterlim** [rallion/depressurizer#74]
I saw this issue when launching depressurizer.

I suspect is due to ABZU game > http://store.steampowered.com/app/384190/
Any games after this in my steam game list do not appear in depressurizer

appID: 384190
name: ABZÛ

Using version 0.6.1.0

Added log:

> 22:55:20.964839 - INFO: Integrated XML data into game list. 155 total items, 0 new.
22:59:16.231713 -  ERR: Exception when performing local update.
Depressurizer.ParseException: Unexpected character '36' found when expecting key.
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.PackageInfo.LoadPackages(String path)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
   at Depressurizer.FormMain.UpdateLibrary()

**Comment by Grief** [comment]
I have a similar issue with character '22', not sure what game is it though.

**Comment by DeMyztikX** [comment]
I had this with '25' and am missing something around 300-400 games from the list. Aaru's Awakening is the first one I noticed missing (alphabetically first).

Theo's version seems to work just fine though.

**Comment by Shad3w** [comment]
Theo's Version?

**Comment by Hacksterlim** [comment]
I'll go try out Theo's version. Will report back after trying out.

**Comment by VincEmond** [comment]
I have the same error with '37'. I do not have the game Aaru's Awakening however.

**Comment by Fungusface** [comment]
I have the same error with '109'. Not sure what game it's associated with, but the app is only picking up 562 of my 697 games.

**Comment by DeMyztikX** [comment]
@fungusface @VincEmond new version by Theo https://github.com/Theo47/depressurizer

This one isn't maintained any more.

**Comment by Fungusface** [comment]
Thanks. Theo version works great!

**Comment by VincEmond** [comment]
Great, thanks for the new version update !
