### ISSUE TITLE
Unexpected character '110' found when expecting key.

### ISSUE THREAD

**Issue by Godsofsalt** [rallion/depressurizer#77]
https://gyazo.com/859caa76f7f07c0f79aae74b80a55836

**Comment by Godsofsalt** [comment]
System.ApplicationException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Depressurizer.GameList.FetchHtmlFromUrl(String url)
   --- End of inner exception stack trace ---
   at Depressurizer.GameList.FetchHtmlFromUrl(String url)
   at Depressurizer.GameList.FetchHtmlGameList(Int64 accountId)
   at Depressurizer.CDlgUpdateProfile.FetchHtml()
   at Depressurizer.CDlgUpdateProfile.FetchXmlPref()
   at Depressurizer.CDlgUpdateProfile.RunProcess()
   at Rallion.CancelableDlg.RunProcessChecked()
08:53:22.863195 - INFO: Program closing.

**Comment by ericd7** [comment]
Also getting this issue. It wont update the game list properly after it throws it.

**Comment by endlessknife** [comment]
Try this more recent fork https://github.com/Theo47/depressurizer/releases @ericd7
