### ISSUE TITLE
Unexpected character '11' found when expecting key

### ISSUE THREAD

**Issue by wooby6** [rallion/depressurizer#82]
11:24:54.098964 -  ERR: Exception when performing local update.
Depressurizer.ParseException: Unexpected character '11' found when expecting key.
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.PackageInfo.LoadPackages(String path)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
   at Depressurizer.FormMain.UpdateLibrary()

Full log at [https://pastebin.com/QfiWZf2k](https://pastebin.com/QfiWZf2k)

**Comment by FMastro** [comment]
I'm having this same issue.

**Comment by CptChaos** [comment]
I'm having same error, but for character 37. App continues after clicking OK, but doesn't seem to categorize my library. On Windows 10.

EDIT:
https://github.com/Depressurizer/Depressurizer seems a fork which still has active development.

**Comment by mvegter** [comment]
@CptChaos The fork you mentioned isn't active anymore, you can try my branch: [mvegter/Depressurizer](https://github.com/mvegter/Depressurizer). I'm one of the contributors of the fork you mentioned.

**Comment by CptChaos** [comment]
@mvegter Thanks! I see your fork has more featuers too! Nice! Will use that one, hahaha!
