### ISSUE TITLE
Unexpected character 7

### ISSUE THREAD

**Issue by PauloWar** [rallion/depressurizer#90]

**Comment by UmbraAtrox** [comment]
![image](https://user-images.githubusercontent.com/33509547/227020131-0c17a1ac-9c7e-430c-861d-bb2ef628a901.png)
Same error different character

**Comment by murphycd** [comment]
I have the same error.
```
16:43:16.843236 - INFO: Profile loaded.
16:43:24.665383 -  ERR: Exception when performing local update.
Depressurizer.ParseException: Unexpected character '213' found when expecting key.
   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   at Depressurizer.PackageInfo.LoadPackages(String path)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
   at Depressurizer.FormMain.UpdateLibrary()
```
